name: threads
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Sans
      fonts:
        - asset: fonts/InstagramSans-Light.ttf
          weight: 300
        - asset: fonts/InstagramSans-Regular.ttf
          weight: 400
        - asset: fonts/InstagramSans-Medium.ttf
          weight: 500
        - asset: fonts/InstagramSans-Bold.ttf
          weight: 700  

  assets:
      - assets/    

